version: '3'

services:
  clash:
    image: chenxinaz/clash_gw:alpine
    # privileged: true  # replaced by cap_add
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/:/clash
    networks:
      macnet:
      clash:
    restart: unless-stopped
    entrypoint: ['/clash/entrypoint.sh']
networks:
  clash:
  macnet:
    external: true
