name: ci

on:
  push:
    branches: master
    tags: '*'

jobs:
  multi:
    runs-on: ubuntu-latest
    environment: push_dockerhub
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ DOCKERHUB_REPO }}:latest
            ${{ DOCKERHUB_REPO }}:v0.19.0
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ DOCKERHUB_REPO }}:alpine-latest
            ${{ DOCKERHUB_REPO }}:alpine
            ${{ DOCKERHUB_REPO }}:alpine-v0.19.0
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
          repository: chenxinaz/clash
