name: ci

on:
  push:
    tags: '*'

jobs:
  multi:
    runs-on: ubuntu-latest
    environment: push_dockerhub
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            chenxinaz/clash_gw:latest
            chenxinaz/clash_gw:${{ github.ref }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            chenxinaz/clash_gw:alpine-latest
            chenxinaz/clash_gw:alpine
            chenxinaz/clash_gw:alpine-${{ github.ref }}
